baseURL = "https://erikaurano.com/"
title = "Erika Urano"
theme = "erikaurano-theme"

# SEO Settings
description = "Erika Urano is a filmmaker and artist specializing in narrative films and production design. Explore her portfolio of films, art, and creative work."


[mediaTypes]
  [mediaTypes."application/vnd.apple.mpegurl"]
    suffixes = ["m3u8"]

  [mediaTypes."video/MP2T"]
    suffixes = ["ts"]

[outputFormats]
  [outputFormats.M3U8]
    mediaType = "application/vnd.apple.mpegurl"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[params]
  [[params.navItems]]
    name = "Films"
    image = "images/director.gif"
    url = "/films/"

  [[params.navItems]]
    name = "Art"
    image = "images/art.gif"
    url = "/art/"

  [[params.navItems]]
    name = "About"
    image = "images/about.gif"
    url = "/about/"

  [[params.films]]
    title = "Nowhere to Hide"
    playlist = "/films/NowhereToHide/master.m3u8"
    preview = "/images/NowhereToHide.jpg"
    roles = ["Director", "Writer"]
    year = "2023"

  [[params.films]]
    title = "The Room without Walls"
    playlist = "/films/TheRoomWithoutWalls/master.m3u8"
    preview = "/images/TheRoomWithoutWalls.jpg"
    roles = ["Director", "Production Designer"]
    year = "2022"

  [[params.films]]
    title = "Ton Poertefeuille"
    playlist = "/films/TonPoertefeuille/master.m3u8"
    preview = "/images/TonPoertefeuille.jpg"
    roles = ["Writer", "Production Designer"]
    year = "2022"

  [[params.films]]
    title = "You Loved to Dance"
    playlist = "/films/YouLovedToDance/master.m3u8"
    preview = "/images/YouLovedToDance.jpg"
    roles = ["Director"]
    year = "2021"
